app/models.py
from app import db
from datetime import datetime
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
class User(UserMixin,db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer,primary_key = True)
    username= db.Column(db.String(300),unique = True,index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    pass_s =db.Column(db.String(300))
    profile_pic_path = db.Column(db.String(255))
    bio = db.Column(db.String(600))
    posted = db.Column(db.DateTime, default=datetime.utcnow)
    blogs = db.relationship('Blog', backref='users', lazy='dynamic')
    upvote = db.relationship('Upvote', backref = 'users', lazy = 'dynamic')
    downvote = db.relationship('Downvote', backref = 'users', lazy = 'dynamic')
  
 
    @property
    def password(self):
      raise AttributeError('this is restriced')
  
    @password.setter
    def password(self,password):
        self.pass_s = generate_password_hash(password)
        
    def verify_hash(self,password):
        return check_password_hash(self.pass_s, password)
    
    def __repr__(self):
        return f'User{self.username}'
    
class Blog(db.Model):
    __tablename__ = 'blogs'
    
    id = db.Column(db.Integer,primary_key = True)
    blog = db.Column(db.String(500),index = True)
    posted = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"), nullable = False)
    comments = db.relationship('Comment',backref='blogs',lazy='dynamic') 
    upvotes = db.relationship('Upvote', backref = 'blogs', lazy = 'dynamic')
    downvotes = db.relationship('Downvote', backref = 'blogs', lazy = 'dynamic')
    
    def __repr__(self):
       return f'Blog{self.description}'
   
class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(200))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))

    def __repr__(self):
        return f'<Comment: {self.comment}>'


class Upvote(db.Model):
    __tablename__ = 'upvotes'
    
    id = db.Column(db.Integer,primary_key = True)
    upvote = db.Column(db.Integer,default=1)
    blog_id = db.Column(db.Integer,db.ForeignKey('blogs.id'))
    author_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    
    def __repr__(self):
       return f'Upvote{self.upvotes}'
   
class Downvote(db.Model):
    __tablename__ = 'downvotes'
    
    id = db.Column(db.Integer,primary_key = True)
    downvote = db.Column(db.Integer,default=1)
    blog_id = db.Column(db.Integer,db.ForeignKey('blogs.id'))
    author_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    
    def __repr__(self):
       return f'Downvote{self.downvotes}'
    
  

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from .config import config_options
from flask_login import LoginManager


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
      # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    
    # from .request import configure_request
    # configure_request(app)
    
   


    # Initializing flask extensions
    

    return app

app/main/__init__.py
from flask import Blueprint 

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import redirect, render_template,url_for,abort
from flask_login import current_user
from app.main.form import  BlogForm, CommentForm
from app.main import main
from app import db
from ..models import Comment,Blog

@main.route('/')
def index():
    blogs=Blog.query.all()
    comments = Comment.query.all()
    form = CommentForm()
    return render_template('index.html',blogs=blogs,comments=comments,form=form)

@main.route('/blog', methods=["GET","POST"])
def blog():
    form=BlogForm()
    if form.validate_on_submit():
        blog=Blog(blog=form.blog.data,user_id=current_user.id)
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('blog.html', form=form)

@main.route('/comment', methods= ["GET","POST"])
def comment():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(comment = form.comment.data, user_id=current_user)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('comment.html', form = form)

@main.route('/blog', methods= ["POST"])
def delete_blog():
    blog = Blog.query.get_or_404()
    if blog.user_id !=current_user:
        abort(403)
    db.session.delete(blog)
    db.session.commit()
    return redirect(url_for('main.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/index.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BLOG IT UP</title>
</head>
<body>
 
    {%block content%}

{% endblock %}

</body>
</html>

app/templates/blog.html
{% extends 'base.html'%} {%block content%}
<div class="back_add">
  <section class="container">
    <form action="" method="post">
      {{ form.csrf_token }}
      <h3>Add a blog</h3>
      <div class="form-group">
        {{ form.blog.label(class='form-label') }} {{
        form.blog(class='form-control') }}
      </div>
      <div class="col-sm">
        <p>{{ form.submit() }}</p>
      </div>
      <a class="nav-item nav-link text-dark" href="{{url_for("main.index")}}">BACK </a>
    </form>
  </section>
</div>
{%endblock%}

app/templates/comment.html
{% extends 'base.html' %}

<!-- hero section -->
{% block content %}
<div class="back-comm">
  <!-- comment intput box -->
  <form action="" method="post">
    {{ form.csrf_token }}
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <input type="text" id="comment" placeholder="Add comment...." />
        </div>
        <div class="col-sm">
          <button type="submit bg-primary " class="btn-submit">submit</button>
           <a class="nav-item nav-link " href="{{url_for("main.index")}}">BACK </a>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%} {%block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-primary">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{{url_for("main.index")}}">Home <span class="sr-only">(current)</span></a>

      {%if current_user.is_authenticated %}
      <a class="nav-item nav-link " href="{{ url_for('auth.logout') }}">LOGOUT</a>
      {%else%}
     
      <a class="nav-item nav-link " href="{{url_for("auth.login")}}">LOGIN</a>
      {%endif%}
    </div>
  </div>
</nav>


<div class="bg">
     {% if current_user.is_authenticated %}
  <h3 class="text-dark"><i>Welcome {{current_user.username}}</i></h3>
  {% else %}
  <h3>Welcome home</h3>
  {% endif %}
  <section class="smb-hero-section">
    <div class="smb-hero-text">
      <div>
        <h3>BLOG <span> ALL DAY EVERYDAY</span></h3>
        <p>
          Welcome to your personal favourite blog where you are free to say
          anything and everything.<br />
          Anything you need we have it right here
        </p>
        <div class="back-blog"></div>
        <div class="display">
        {%for blog in blogs%}
        <span
          >blog:</span>
          <p>{{blog.blog}}</p>
        <p>{{blog.user_id}}</p>
        <p>{{blog.comment}}</p>
   <a class="nav-item nav-link text-black-10 " href="{{url_for("main.comment")}}">ADD COMMENT</a>
    <div class="">
             <a class="nav-item nav-link " href="{{url_for("main.index")}}">Delete blog</a>
        </div>
        {%endfor%}
        </div>
       
        <div >
            <a class="nav-item nav-link " href="{{url_for("main.blog")}}">ADD blog</a>
        </div>
      </div>
    </div>
  </section>
</div>
{%endblock%}